Metrics/LineLength:
  Max: 120

Metrics/MethodLength: 
  Max: 20

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 19

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 9
  
Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolArray:
  Enabled: true

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

Style/PreferredHashMethods:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    reduce: "reduce"

Layout/MultilineOperationIndentation:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise

Layout/SpaceInsideBlockBraces:
  SpaceBeforeBlockParameters: true

Style/BlockDelimiters:
  Enabled: false

Style/Documentation:
  Enabled: false 

Style/MethodDefParentheses:
  Enabled: true